# Pandas Data Analysis

### Here I analyze the dataset again using Pandas

Importing the pandas and csv file readers and libraries so that I can read in a view my dataset in Python rather than as the file.

In [1]:
import csv
import pandas as pd

This code below simply shows me my dataset so that I know it imported correctly.

In [2]:
faa_data_pandas = pd.read_csv("Pennsylvania_Condensed.csv") # Bringing in the Facebook message data
faa_data_pandas.head()

,INCIDENT_DATE,AIRPORT_ID,AIRPORT,ATYPE,SPECIES_ID,SPECIES,DAMAGE,REMAINS_COLLECTED,REMAINS_SENT,INCIDENT_MONTH,...,DISTANCE,PHASE_OF_FLT,EFFECT,SKY,PRECIP,BIRDS_SEEN,BIRDS_STRUCK,SIZE,WARNED,REMARKS
0,12/14/2017 12:00:00 AM,KPHL,PHILADELPHIA INTL,B-737-800,J2204,Canada goose,M?,True,False,12,...,10.0,Approach,None,No Cloud,None,11 to 100,1,Large,N,Flock of geese at our altitude. One struck the...
1,11/20/2017 12:00:00 AM,KPNE,NORTHEAST PHILADELPHIA ARPT,C-210 CENTUR,UNKBM,Unknown bird - medium,N,True,False,11,...,0.0,Climb,Precautionary Landing,No Cloud,None,1,1,Medium,N,no damage
2,11/17/2017 12:00:00 AM,KPHL,PHILADELPHIA INTL,A-321,J2204,Canada goose,M?,False,False,11,...,NaN,Climb,Precautionary Landing,No Cloud,None,11 to 100,2 to 10,Large,N,"DENTS FUSELAGE, FLAP TRACK BEARING."
3,11/10/2017 12:00:00 AM,KPIT,PITTSBURGH INTL ARPT,CRJ700,UNKBL,Unknown bird - large,M?,False,False,11,...,3.0,Approach,None,Overcast,None,2 to 10,1,Large,Y,CRACKED RADOME POSSIBLE BENT FRAME BEHIND IT
4,11/10/2017 12:00:00 AM,KPHL,PHILADELPHIA INTL,A-321,UNKBL,Unknown bird - large,N,False,False,11,...,NaN,Climb,None,No Cloud,None,NaN,2 to 10,Large,N,NaN

Besides just seeing that I could properly display the data, I needed to make sure it imported the whole spreadsheet. By displaying the shape of the data I was able to see that all 6167 lines did in fact get imported. This also shows that all 25 rows did as well.

In [3]:
faa_data_pandas.shape

(6167, 25)

This is how you pull out just one type. This case pulls out only the instances where the Airport_ID is true for KPHL, then displays just the first few rows. I did this just to test my ability to see just certain subsets of the data. This skill is helpful when analysing the data later in the project.

In [4]:
# Create a new dataframe for the Airport ID (It does so by testing true/false on date equaling 2018-05-31)
faa_data_phil_pandas = faa_data_pandas[faa_data_pandas['AIRPORT_ID'] == "KPHL"]

print(faa_data_phil_pandas.shape)
faa_data_phil_pandas.head()

(2267, 25)

,INCIDENT_DATE,AIRPORT_ID,AIRPORT,ATYPE,SPECIES_ID,SPECIES,DAMAGE,REMAINS_COLLECTED,REMAINS_SENT,INCIDENT_MONTH,...,DISTANCE,PHASE_OF_FLT,EFFECT,SKY,PRECIP,BIRDS_SEEN,BIRDS_STRUCK,SIZE,WARNED,REMARKS
0,12/14/2017 12:00:00 AM,KPHL,PHILADELPHIA INTL,B-737-800,J2204,Canada goose,M?,True,False,12,...,10.0,Approach,None,No Cloud,None,11 to 100,1,Large,N,Flock of geese at our altitude. One struck the...
2,11/17/2017 12:00:00 AM,KPHL,PHILADELPHIA INTL,A-321,J2204,Canada goose,M?,False,False,11,...,NaN,Climb,Precautionary Landing,No Cloud,None,11 to 100,2 to 10,Large,N,"DENTS FUSELAGE, FLAP TRACK BEARING."
4,11/10/2017 12:00:00 AM,KPHL,PHILADELPHIA INTL,A-321,UNKBL,Unknown bird - large,N,False,False,11,...,NaN,Climb,None,No Cloud,None,NaN,2 to 10,Large,N,NaN
7,10/28/2017 12:00:00 AM,KPHL,PHILADELPHIA INTL,B-737-700,L6001,Wild turkey,N,False,False,10,...,NaN,Approach,None,Some Cloud,None,1,1,Large,Y,LOTS OF BIRD DEBRIS BUT APPEARS WENT THROUGH E...
11,9/20/2017 12:00:00 AM,KPHL,PHILADELPHIA INTL,A-321,UNKBS,Unknown bird - small,N,False,False,9,...,4.0,Approach,None,No Cloud,None,NaN,2 to 10,Small,N,None seen. Just remains.

This is the Pandas method for counting the instances of a categorical dataset, such as in this case airport id. This below counts the dataset and each time it finds a new value in the airport field it makes a counter for it, which goes up with each time it passes an occurance. This shows me which airport has more occurances of animal strikes.

In [5]:
airport_count = faa_data_pandas['AIRPORT'].value_counts()
print(airport_count)

PHILADELPHIA INTL                            2267
PITTSBURGH INTL ARPT                         1611
HARRISBURG INTL                               892
LEHIGH VALLEY INTL                            432
WILKES-BARRE/SCRANTON INTL                    192
ERIE INTL ARPT-TOM RIDGE FIELD                147
UNIVERSITY PARK ARPT                           96
ALLEGHENY COUNTY ARPT                          83
READING REGNL ARPT/CARL A SPAATZ FIELD         83
NORTHEAST PHILADELPHIA ARPT                    57
LANCASTER ARPT (PA)                            40
WILLIAMSPORT REGIONAL ARPT                     33
CAPITAL CITY ARPT (PA)                         29
CHESTER COUNTY G O CARLSON ARPT                25
ARNOLD PALMER REGIONAL                         23
JOHN MURTHA JOHNSTOWN-CAMBRIA COUNTY ARPT      23
DUBOIS REGIONAL ARPT                           22
ALTOONA-BLAIR COUNTY                           21
VENANGO REGIONAL                               13
BEAVER COUNTY ARPT                             11
BRADFORD REGIONAL                              10
WASHINGTON COUNTY                              10
WINGS FIELD ARPT                                6
ALLENTOWN QUEEN CITY MUNICIPAL                  5
ROSTRAVER                                       5
ZELIENOPLE MUNICIPAL                            3
SCHUYKILL COUNTY (JOE ZERBEY) ARPT              2
PENNS LANDING HELIPORT                          2
MUIR ARMY AIRFIELD                              2
BRANDYWINE ARPT                                 2
DECK ARPT                                       2
PORT MEADVILLE ARPT                             2
NEW CASTLE MUNICIPAL ARPT                       1
MORGANTOWN ARPT                                 1
HERITAGE FIELD ARPT                             1
BUTLER FARM SHOW                                1
MARIAN HELIPORT                                 1
VANSANT                                         1
GREEN COUNTY                                    1
NEW GARDEN                                      1
ALLEGHENY GEN HOSP EMERG HELIPORT               1
FINLEYVILLE AIRPARK                             1
POCONO MOUNTAINS MUNI ARPT                      1
SPRING HILL ARPT                                1
GREENSBURG JEANETTE REGIONAL ARPT               1
YORK ARPT                                       1
AIR HAVEN ARPT                                  1
DOYLESTOWN ARPT                                 1
Name: AIRPORT, dtype: int64

For ease of importing to my DH project, I then exported this variable into its own spreadsheet so I could then import that into my HTML code.

In [6]:
airport_count.to_excel('airport_count.xlsx')
print("Done Writing!")

Done Writing!

As before with the airport, I repeated this process with animals. This way I could see which animal was struck more often and then split out the mammals from the birds manually since there were so few.

In [7]:
species_count = faa_data_pandas['SPECIES'].value_counts()
print(species_count)

Unknown bird - small      1223
Unknown bird - medium      887
European starling          405
Gulls                      343
Mourning dove              300
Barn swallow               208
Unknown bird               202
Bank swallow               199
Sparrows                   187
American kestrel           174
Killdeer                   126
Canada goose               113
Ring-billed gull           112
Unknown bird - large       103
Tree swallow                97
Swallows                    96
Blackbirds                  82
Horned lark                 80
Red-tailed hawk             76
White-tailed deer           72
Hawks                       71
American robin              55
Rock pigeon                 52
Chimney swift               48
Eastern meadowlark          48
Brown-headed cowbird        38
Red-winged blackbird        38
Ducks                       33
Woodchuck                   25
Big brown bat               24
                          ...
Common yellowthroat          1
Black-capped chickadee       1
American black duck          1
Sharp-shinned hawk           1
Nelson's sparrow             1
Chipping sparrow             1
American tree sparrow        1
Cackling goose               1
Shorebirds                   1
New World Vultures           1
Indigo bunting               1
Barred owl                   1
Mink                         1
American wigeon              1
Broad-winged hawk            1
Wood thrush                  1
Pigeons, doves               1
Blackburnian warbler         1
Black-bellied plover         1
Tundra swan                  1
American redstart            1
Cave swallow                 1
Egrets                       1
Painted turtle               1
Sanderling                   1
Northern pintail             1
Ruddy duck                   1
Chestnut-sided warbler       1
Prairie falcon               1
Caspian tern                 1
Name: SPECIES, Length: 184, dtype: int64

Here I also exported this new variable of the count to an excel spreadsheet so that I could then import this to my html code.

In [8]:
species_count.to_excel('species_output.xlsx')
print("Done Writing!")

Done Writing!

As with the species of animal and the airport I counted each datapoint of damage.

In [9]:
damage_count = faa_data_pandas['DAMAGE'].value_counts()
print(damage_count)

N     4094
M      205
S      125
M?     119
E        3
C        1
D        1
Name: DAMAGE, dtype: int64

Since the letter code within the dataset does not really tell us much. I then took the output of the damage_count vaiable from just above and ran it through code to export the answers in a more human readable format.

In [10]:
damage_lookup_dictionary = {"N": "None",
                            "M": "Minor",
                            "M?": "Unknown",
                            "S": "Substantial",
                            "D": "Destroyed",
                            "A": "Over $2,000,000 (Military)",
                            "B": "$500,000 to $2,000,000 (Military)",
                            "C": "$50,000 - $500,000 (Military)",
                            "E": "Less than $50,000 (Military)",
                            "": "No Damage Reported",}

Here I then run the datase through this dictionary and display the count for each value and show it by the name of the

In [11]:
faa_data_pandas["DAMAGE"].value_counts().rename(index=damage_lookup_dictionary)

None                             4094
Minor                             205
Substantial                       125
Unknown                           119
Less than $50,000 (Military)        3
$50,000 - $500,000 (Military)       1
Destroyed                           1
Name: DAMAGE, dtype: int64

Here I used the same methods to count the damage done at each phase of the flight. This way I could see at what point during the flight the planes make contact with the animals. Later I hope to do some more complex analysis of this portion of the data.

In [12]:
flight_phase = faa_data_pandas['PHASE_OF_FLT'].value_counts()
print(flight_phase)

Approach        2108
Climb            909
Landing Roll     856
Take-off run     742
Descent           94
Departure         34
Landing           22
Taxi              10
Local              9
APPROACH           6
TAKE-OFF RUN       2
Arrival            2
DEPARTURE          1
Landing roll       1
Unknown            1
Name: PHASE_OF_FLT, dtype: int64

For ease of importing to my website, I created a spreadsheet of just this variable counted.

In [13]:
flight_phase.to_excel('flight_phase.xlsx')
print("Done Writing!")

Done Writing!

Here it counts the time of day. There is a time variable, but counting it would prve to be difficult since it is simply input as an integer. Therefore for now I just analyzed the 'time of day' field. I hope to late use the time field and give a more in depth look at the information.

In [14]:
time_of_day = faa_data_pandas['TIME_OF_DAY'].value_counts()
print(time_of_day)

Day      2847
Night    1310
Dusk      202
Dawn      123
Name: TIME_OF_DAY, dtype: int64

While I have not done anything with this portion of the data analysis for the first draft of my project. I began analysing the data as amount of damage done to the aircraft at each airport. I hope to later normalize the data against flights at each location, then combine it with this analysis to see what airport has the most destructive animals at it. Though I lack current skills to normalize the dataset, so I just did the portion that I could for now.

In [15]:
# Create a new dataframe for the Airport ID (It does so by testing true/false on date equaling 2018-05-31)
faa_data_minor_damage_pandas = faa_data_pandas[faa_data_pandas['DAMAGE'] == "M"]

print(faa_data_minor_damage_pandas.shape)
faa_data_minor_damage_pandas.head()

(205, 25)

,INCIDENT_DATE,AIRPORT_ID,AIRPORT,ATYPE,SPECIES_ID,SPECIES,DAMAGE,REMAINS_COLLECTED,REMAINS_SENT,INCIDENT_MONTH,...,DISTANCE,PHASE_OF_FLT,EFFECT,SKY,PRECIP,BIRDS_SEEN,BIRDS_STRUCK,SIZE,WARNED,REMARKS
126,11/17/2016 12:00:00 AM,9D4,DECK ARPT,C-177,K5114,American kestrel,M,False,False,11,...,0.0,Climb,None,No Cloud,None,1,1,Small,Y,Slight damage to the leading edge of the left ...
136,11/6/2016 12:00:00 AM,KPHL,PHILADELPHIA INTL,A-321,UNKBM,Unknown bird - medium,M,False,False,11,...,5.0,Approach,None,No Cloud,None,NaN,2 to 10,Medium,N,5 miles NNW KPHL
285,8/16/2016 12:00:00 AM,KPHL,PHILADELPHIA INTL,A-321,UNKBL,Unknown bird - large,M,False,False,8,...,NaN,APPROACH,None,No Cloud,None,2 to 10,1,Large,N,DAMAGE TO LEFT WING WITH 4 POPPED RIVETS. MOR_...
290,8/15/2016 12:00:00 AM,KPHL,PHILADELPHIA INTL,CRJ700,K1002,Turkey vulture,M,False,False,8,...,NaN,Approach,None,No Cloud,None,2 to 10,1,Large,N,HAS A DENT IN THE RVSM CRITICAL AREA.
450,4/4/2016 12:00:00 AM,KMDT,HARRISBURG INTL,EMB-145,NE1,Gulls,M,True,True,4,...,0.0,Landing Roll,NaN,Overcast,NaN,NaN,1,Medium,NaN,UNDETERMINED SPECIES OF WHITE-HEADED GULL. DNA...

In [16]:
faa_data_minor_damage_pandas['AIRPORT'].value_counts()

PHILADELPHIA INTL                            72
PITTSBURGH INTL ARPT                         25
HARRISBURG INTL                              18
LEHIGH VALLEY INTL                           10
NORTHEAST PHILADELPHIA ARPT                   9
READING REGNL ARPT/CARL A SPAATZ FIELD        9
ERIE INTL ARPT-TOM RIDGE FIELD                7
ALLEGHENY COUNTY ARPT                         6
WILLIAMSPORT REGIONAL ARPT                    5
ALTOONA-BLAIR COUNTY                          4
CAPITAL CITY ARPT (PA)                        4
WILKES-BARRE/SCRANTON INTL                    4
WASHINGTON COUNTY                             3
LANCASTER ARPT (PA)                           3
ROSTRAVER                                     2
WINGS FIELD ARPT                              2
CHESTER COUNTY G O CARLSON ARPT               2
ZELIENOPLE MUNICIPAL                          2
JOHN MURTHA JOHNSTOWN-CAMBRIA COUNTY ARPT     2
ALLENTOWN QUEEN CITY MUNICIPAL                1
UNIVERSITY PARK ARPT                          1
VENANGO REGIONAL                              1
GREENSBURG JEANETTE REGIONAL ARPT             1
BRADFORD REGIONAL                             1
HERITAGE FIELD ARPT                           1
MUIR ARMY AIRFIELD                            1
BEAVER COUNTY ARPT                            1
SCHUYKILL COUNTY (JOE ZERBEY) ARPT            1
FINLEYVILLE AIRPARK                           1
DECK ARPT                                     1
ARNOLD PALMER REGIONAL                        1
BUTLER FARM SHOW                              1
DUBOIS REGIONAL ARPT                          1
ALLEGHENY GEN HOSP EMERG HELIPORT             1
NEW GARDEN                                    1
Name: AIRPORT, dtype: int64

In [17]:
# Create a new dataframe for the Airport ID (It does so by testing true/false on date equaling 2018-05-31)
faa_data_substantial_damage_pandas = faa_data_pandas[faa_data_pandas['DAMAGE'] == "S"]

print(faa_data_substantial_damage_pandas.shape)
faa_data_substantial_damage_pandas.head()

(125, 25)

,INCIDENT_DATE,AIRPORT_ID,AIRPORT,ATYPE,SPECIES_ID,SPECIES,DAMAGE,REMAINS_COLLECTED,REMAINS_SENT,INCIDENT_MONTH,...,DISTANCE,PHASE_OF_FLT,EFFECT,SKY,PRECIP,BIRDS_SEEN,BIRDS_STRUCK,SIZE,WARNED,REMARKS
445,4/11/2016 12:00:00 AM,KPHL,PHILADELPHIA INTL,B-737-700,UNKBL,Unknown bird - large,S,True,False,4,...,0.0,Take-off run,Precautionary Landing,No Cloud,None,1,1,Large,NaN,"BIRD REPORTED AS ""EAGLE/LARGE BIRD OF PREY."" N..."
482,12/13/2015 12:00:00 AM,KPHL,PHILADELPHIA INTL,A-330,J2202,Snow goose,S,True,True,12,...,NaN,Climb,Precautionary Landing,NaN,NaN,1,1,Large,NaN,ASSUME ONE STRUCK. PILOT SAW A WHITE FLASH ARO...
648,8/2/2015 12:00:00 AM,KPHL,PHILADELPHIA INTL,EMB-170,NE1,Gulls,S,False,False,8,...,1.0,Climb,None,No Cloud,None,1,1,Medium,N,LEFT FRONT SIDE OF NOSE CONE HAS A DENT. AIRCR...
807,3/19/2015 12:00:00 AM,KMDT,HARRISBURG INTL,EMB-170,NE104,Ring-billed gull,S,True,False,3,...,NaN,Climb,Precautionary Landing,Some Cloud,None,1,1,Medium,NaN,DURING T/O THERE WAS A LOUD SOUND AFTER BRINGI...
1010,8/20/2014 12:00:00 AM,KMPO,POCONO MOUNTAINS MUNI ARPT,PA-31 NAVAJO,1G11,White-tailed deer,S,True,False,8,...,0.0,Landing Roll,None,Some Cloud,None,NaN,1,Large,N,RT NOSE GEAR DOOR SERIOUSLY DAMAGED. 1 SMALL B...

In [18]:
# Create a new dataframe for the (It does so by testing true/false on date equaling 2018-05-31)
faa_data_destroyed_damage_pandas = faa_data_pandas[faa_data_pandas['DAMAGE'] == "D"]

print(faa_data_destroyed_damage_pandas.shape)
faa_data_destroyed_damage_pandas

(1, 25)

,INCIDENT_DATE,AIRPORT_ID,AIRPORT,ATYPE,SPECIES_ID,SPECIES,DAMAGE,REMAINS_COLLECTED,REMAINS_SENT,INCIDENT_MONTH,...,DISTANCE,PHASE_OF_FLT,EFFECT,SKY,PRECIP,BIRDS_SEEN,BIRDS_STRUCK,SIZE,WARNED,REMARKS
3203,3/6/2009 12:00:00 AM,KAVP,WILKES-BARRE/SCRANTON INTL,UNKNOWN,J2204,Canada goose,D,False,False,3,...,NaN,Climb,NaN,NaN,NaN,NaN,NaN,Large,NaN,NaN